[project]
name = "browsing-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use>=0.5.4",
    "playwright>=1.53.0",
]
